[package]
name = "rpawomaster"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
rand_chacha = "0.3"
unicode-segmentation = "1.10"
zxcvbn = "3.1.0"
